### ISSUE TITLE
No visible @interface for 'iZettleSDK' for 'retrievePaymentInfoForReference:completion'

### ISSUE THREAD

**Issue by asa47** [ttopholm/iZettle#2]
Hi, I'm integrating iZettle with cordova ios App, I followed the instructions on https://github.com/iZettle/sdk-ios, and added the plugin in the cordova project; however once I build it, I received the following error:

k.sugee.iZettle/iZettlePlugin/iZettle.m:73:26: error: no visible @interface for 
'iZettleSDK' declares the selector 'retrievePaymentInfoForReference:completion:' 
[[iZettleSDK shared] retrievePaymentInfoForReference:retrievePaymentInfoForR
eference completion:^(iZettleSDKPaymentInfo *paymentInfo, NSError *error) {

**Comment by ttopholm** [comment]
@asa47, the code hasn't been updated to the latest iZettle SDK, so that is the issue. I'll see if I can fix it

**Comment by asa47** [comment]
@ttopholm Thanks for the reply.

**Comment by asa47** [comment]
Hello, would it be possible to know how long could it take to update the plugin to the latest iZettle SDK?
Regards.

**Comment by asa47** [comment]
Hello, I was wondering if I could fork your repository and push the up to date version of the plugin, I removed a couple of functions and kept it simple. Let me know if it is fine.
Regards.

**Comment by fabgrenier** [comment]
Hello @asa47 and @ttopholm, we would like to know if you found a deal to allow asa47 to release an updated plugin. Thanks
